- name: Create a session and token to use
  hosts: localhost
  connection: local
  gather_facts: false

  # credentials for iDRAC
  vars:
    baseuri: 10.0.0.89
    username: root
    password: r0gerwilc0

  collections:
    community.general

  tasks:
  - name: create session
    community.general.redfish_command:
      category: Sessions
      command: CreateSession
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: show results of the session
    debug:
        var: result

  - name: reflect on session and token information
    pause:

  # notice that we no longer are using a password and username combo
  # instead we can use the token we tracked down
  - name: get info using a token not a password and username
    community.general.redfish_info:
      baseuri: "{{ baseuri }}"
      auth_token: "{{ result.session.token }}"
    register: results

  - name: show facts we retrieved with session token
    debug:
        var: result

  - name: show results of the facts
    pause:

  - name: Get  GetBiosAttributes
    community.general.redfish_info:
      category: Systems
      command:  GetBiosAttributes
      baseuri: "{{ baseuri }}"
      auth_token: "{{ result.session.token }}"
    register:  biosAttributes

  - name: show facts we retrieved with session token
    debug:
        var: biosAttributes

  - name: Pause to check biosAttributes
    pause:

  - name: Verify BIOS attributes - MemType LogicalProc  PerfOptimized
    community.general.redfish_command:
      category: Systems
      command: VerifyBiosAttributes
      baseuri: "{{ baseuri }}"
      auth_token: "{{ result.session.token }}"
      bios_attributes:
         SysMemType: "ECC DDR4"
         LogicalProc: "Enabled"
         SysProfile: "PerfOptimized"

  - name: check verify bios attributes
    pause:

# trash the token, we are done with it
  - name: Delete the Session
    community.general.redfish_command:
       category: Sessions
       command: DeleteSession
       baseuri: "{{ baseuri }}"
       auth_token: "{{ result.session.token }}"
       session_uri: "{{ result.session.uri }}" 
