- name: Use Redfish to gather CPU Inventory, and Virtual media Information
  hosts: Redfish
  connection: local
  gather_facts: false

  collections:
    community.general

  tasks:
  - name: Get CPU Inventory
    community.general.redfish_info:
      category: Systems
      command: GetCpuInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: cpuInv

  - name: Display CPU data
    debug:
      var: cpuInv

