- name: Use Redfish to gather CPU Inventory, and Virtual Media Information
  hosts: Redfish
  connection: local
  gather_facts: false

  collections:
    community.general

  tasks:
  - name: Get Chassis Health
    community.general.redfish_info:
      category: Chassis
      command: GetHealthReport
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: chassisHealth

  - name: Display Chassis Health
    debug:
      var: chassisHealth
