---
- name: PRECHECKING - Check Health of iDRAC
  block:

  - name: Show status of the Lifecycle Controller
    dellemc.openmanage.idrac_lifecycle_controller_status_info:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      validate_certs: False
    register: results
  - name: Show us what you learned
    debug:
      var: results


  # The glass is half full
  - name: ASSERT is a "postive" way to think
    assert:
      that: results.lc_status_info.LCReady == true
      success_msg: iDRAC is healthy
      fail_msg: iDRAC is unhealthy

  # The glass is half empty
  - name: FAIL is a "negative" way to think (just reverse the assert logic!)
    fail:
      msg: Failing on confirmation of iDRAC health
    when: results.lc_status_info.LCReady != true

  rescue:

  - name: Collect Logs when idrac is unhealthy"
    dellemc.openmanage.idrac_lifecycle_controller_status_info:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      validate_certs: False
      share_name: "/example/export_lc"
  #     when: results.lc_status_info.LCReady != true or results.lc_status_info.LCStatus != "Ready"


  - name: PRECHECK FAIL - Exit the playbook
    fail:
      msg: "Precheck failed. Exiting the playbook"

